-- Camera brand + connection metadata (safe to re-run)
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS brand VARCHAR(30) DEFAULT 'custom';
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS connection_mode VARCHAR(20) DEFAULT 'pull';
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS host VARCHAR(100);
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS port INT DEFAULT 554;
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS username VARCHAR(100);
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS channel INT DEFAULT 1;
